version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ${PWD}/postgres/initdb.d:/docker-entrypoint-initdb.d
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      default:
        ipv4_address: 172.21.0.3

  snmpsim:
    build: snmpsim/.
    restart: unless-stopped
    volumes:
      - ${PWD}/snmpsim/files:/usr/local/snmpsim/data
    ports:
     - "1024:1024"
    networks:
      default:
        ipv4_address: 172.21.0.2

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
volumes:
  postgres-storage:


