version: '3.1'

services:
  db-dev:
    image: postgres
    restart: always
    volumes:
      - ${PWD}/postgres/initdb.d-dev:/docker-entrypoint-initdb.d
      - postgres-storage-prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  snmpsim:
    build: snmpsim/.
    restart: unless-stopped
    user: "snmpsim:nogroup"
    ports:
     - "1024:1024/udp"

  

networks:
  default:

volumes:
  postgres-storage-prod:


